[package]
name = "glfw"
version = "2026.0.01"
edition = "2026"
lang_version = "2026.0.01"

[workspace]
members = ["app", "app-run", "app-vulkan"]

[[products]]
kind = "lib"
root = "lib.rna"

[[native_links]]
name = "glfw3"
