[package]
name = "runa_app"
version = "2026.0.01"
edition = "2026"
lang_version = "2026.0.01"

[[products]]
kind = "lib"
root = "lib.rna"

[dependencies]
glfw = { path = ".." }

[[native_links]]
name = "kernel32"
