[package]
name = "runa_app_vulkan_smoke"
version = "2026.0.01"
edition = "2026"
lang_version = "0.00"

[dependencies]
runa_app = { path = "../../app" }
runa_app_vulkan = { path = "../../app-vulkan" }

[[products]]
kind = "bin"
root = "main.rna"
